-- PostgreSQL target schema after AWS SCT review.
CREATE SCHEMA IF NOT EXISTS orders_app;

CREATE TYPE orders_app.order_status AS ENUM ('pending', 'paid', 'cancelled');

CREATE TABLE orders_app.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customers_email UNIQUE (email)
);

CREATE TABLE orders_app.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status orders_app.order_status NOT NULL DEFAULT 'pending',
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
        REFERENCES orders_app.customers(customer_id)
);

CREATE INDEX ix_orders_customer_created
    ON orders_app.orders (customer_id, created_at);

CREATE TABLE orders_app.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku VARCHAR(64) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES orders_app.orders(order_id)
);

CREATE INDEX ix_order_items_order
    ON orders_app.order_items (order_id);
